export const STATE_PORTALS: Record<string, { url: string; agency: string }> = {
  Alabama: { url: 'https://www.alabamaag.gov/divisions/consumer-interest-division/', agency: 'Attorney General' },
  Alaska: { url: 'https://law.alaska.gov/department/civil/consumer/charityreg.html', agency: 'Dept. of Law' },
  Arizona: { url: 'https://azsos.gov/business/other-services/veterans-charities-organizations', agency: 'Secretary of State' },
  Arkansas: { url: 'https://www.sos.arkansas.gov/business-commercial-services-bcs/nonprofit-charitable-entities/charitable-entities', agency: 'Secretary of State' },
  California: { url: 'https://oag.ca.gov/charities', agency: 'Attorney General' },
  Colorado: { url: 'https://www.coloradosos.gov/pubs/charities/charitableHome.html', agency: 'Secretary of State' },
  Connecticut: { url: 'https://portal.ct.gov/dcp/charities/public-charities', agency: 'Consumer Protection' },
  Delaware: { url: 'https://attorneygeneral.delaware.gov/fraud/', agency: 'Dept. of Justice' },
  'District of Columbia': { url: 'https://dlcp.dc.gov/node/1618416', agency: 'DLCP' },
  Florida: { url: 'https://www.fdacs.gov/Business-Services/Solicitation-of-Contributions', agency: 'FDACS' },
  Georgia: { url: 'https://sos.ga.gov/charities-division-georgia-secretary-states-office', agency: 'Secretary of State' },
  Hawaii: { url: 'https://charity.ehawaii.gov/charity/', agency: 'Attorney General' },
  Idaho: { url: 'https://www.ag.idaho.gov/consumer-protection/', agency: 'Attorney General' },
  Illinois: { url: 'https://www.illinoisattorneygeneral.gov/consumer-protection/charities/', agency: 'Attorney General' },
  Indiana: { url: 'https://www.in.gov/attorneygeneral/consumer-protection-division/charities-and-donors/', agency: 'Attorney General' },
  Iowa: { url: 'https://www.iowaattorneygeneral.gov/for-businesses/professional-fundraisers-and-charity-information--registration/', agency: 'Dept. of Justice' },
  Kansas: { url: 'https://www.sos.ks.gov/businesses/businesses.html', agency: 'Secretary of State' },
  Kentucky: { url: 'https://www.ag.ky.gov/about/Office-Divisions/OCP/Pages/default.aspx', agency: 'Attorney General' },
  Louisiana: { url: 'https://www.ag.state.la.us/Charities', agency: 'Dept. of Justice' },
  Maine: { url: 'https://www.maine.gov/pfr/professionallicensing/professions/charitable/index.html', agency: 'DPFR' },
  Maryland: { url: 'https://sos.maryland.gov/Charity/Pages/Registering-Charity.aspx', agency: 'Secretary of State' },
  Massachusetts: { url: 'https://www.mass.gov/ago/doing-business-in-massachusetts/public-charities-or-not-for-profits/', agency: 'Attorney General' },
  Michigan: { url: 'https://www.michigan.gov/consumerprotection/charities', agency: 'Attorney General' },
  Minnesota: { url: 'https://www.ag.state.mn.us/charity/', agency: 'Attorney General' },
  Mississippi: { url: 'https://www.sos.ms.gov/charities', agency: 'Secretary of State' },
  Missouri: { url: 'https://ago.mo.gov/divisions/consumer/', agency: 'Attorney General' },
  Montana: { url: 'https://dojmt.gov/office-of-consumer-protection/donations-to-charities/', agency: 'Dept. of Justice' },
  Nebraska: { url: 'https://protectthegoodlife.nebraska.gov/', agency: 'Attorney General' },
  Nevada: { url: 'https://nvsos.gov/sos/licensing/charitable-organizations', agency: 'Secretary of State' },
  'New Hampshire': { url: 'https://www.doj.nh.gov/bureaus/charitable-trusts', agency: 'Dept. of Justice' },
  'New Jersey': { url: 'https://www.njconsumeraffairs.gov/charities/Pages/default.aspx', agency: 'Consumer Affairs' },
  'New Mexico': { url: 'https://www.nmag.gov/about-the-office/consumer-affairs/#charities', agency: 'Attorney General' },
  'New York': { url: 'https://www.charitiesnys.com/', agency: 'Attorney General' },
  'North Carolina': { url: 'https://www.sosnc.gov/divisions/charities', agency: 'Secretary of State' },
  'North Dakota': { url: 'https://www.sos.nd.gov/business/nonprofit-services/charitable-organizations', agency: 'Secretary of State' },
  Ohio: { url: 'https://charitable.ohioago.gov/Charity-Registration', agency: 'Attorney General' },
  Oklahoma: { url: 'https://www.sos.ok.gov/charity/Default.aspx', agency: 'Secretary of State' },
  Oregon: { url: 'https://www.doj.state.or.us/charitable-activities/', agency: 'Dept. of Justice' },
  Pennsylvania: { url: 'https://www.pa.gov/agencies/dos/programs/charities', agency: 'Dept. of State' },
  'Rhode Island': { url: 'https://dbr.ri.gov/banking-securities-and-charitable-organizations/securities-and-charities', agency: 'DBR' },
  'South Carolina': { url: 'https://sos.sc.gov/online-filings/charities-pfrs-and-raffles', agency: 'Secretary of State' },
  'South Dakota': { url: 'https://consumer.sd.gov/fastfacts/charity.aspx', agency: 'Attorney General' },
  Tennessee: { url: 'https://sos.tn.gov/charities', agency: 'Secretary of State' },
  Texas: { url: 'https://www.texasattorneygeneral.gov/cpd/charities-nonprofits-registration-filings', agency: 'Attorney General' },
  Utah: { url: 'https://dcp.utah.gov/', agency: 'Consumer Protection' },
  Vermont: { url: 'https://ago.vermont.gov/', agency: 'Attorney General' },
  Virginia: { url: 'https://www.vdacs.virginia.gov/food-charitable-solicitation.shtml', agency: 'VDACS' },
  Washington: { url: 'https://www.sos.wa.gov/corporations-charities/nonprofits-charities/charitable-organizations', agency: 'Secretary of State' },
  'West Virginia': { url: 'https://sos.wv.gov/business/Pages/Charities.aspx', agency: 'Secretary of State' },
  Wisconsin: { url: 'https://dfi.wi.gov/Pages/BusinessServices/CharitableProfessionalOrganizations/GeneralInformation.aspx', agency: 'DFI' },
  Wyoming: { url: 'https://ag.wyo.gov/law-office-division/consumer-protection-and-antitrust-unit', agency: 'Attorney General' },
};
